name: Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: "The remote server url"
        required: true
        default: "http://127.0.0.1"

      port:
        description: "The remote server port"
        required: true
        default: "5099"

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Install Yarn
        run: |
          npm install --global yarn
          npm install --global npm@latest

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Config
        run: |
          echo 'module.exports = {url: "${{ github.event.inputs.url }}", port: ${{ github.event.inputs.port }}};' > ./config.js
          cat ./config.js

      - name: COPY package.json
        run: |
          cp ./package.mac.json package.json
          cat ./package.json

      - name: Install Electron Forge
        run: |
          npm install
          npm install --save-dev @electron-forge/cli
          npm install --save-dev @electron-forge/maker-squirrel
          npm install --save-dev @electron-forge/maker-zip
          npm install --save-dev @electron-forge/maker-dmg
          npm install --save-dev @electron-forge/maker-deb
          npm install --save-dev @electron-forge/maker-rpm
          npx electron-forge import

      - name: Make Artifacts
        run: |
          npm run make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yao-knowledge-darwin-x64
          path: |
            out/make/zip/darwin/x64
  Windows:
    runs-on: windows-latest
    steps:
      - name: Install Yarn
        run: |
          npm install --global yarn
          npm install --global npm@latest

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Config
        run: |
          echo 'module.exports = {url: "${{ github.event.inputs.url }}", port: ${{ github.event.inputs.port }}};' > .\config.js
          cat .\config.js

      - name: COPY package.json
        run: |
          copy .\package.win.json .\package.json
          cat  .\package.json

      - name: Install Electron Forge
        run: |
          npm install --save-dev @electron-forge/cli
          npm install --save-dev @electron-forge/maker-squirrel
          npm install --save-dev @electron-forge/maker-zip
          npm install --save-dev @electron-forge/maker-dmg
          npm install --save-dev @electron-forge/maker-deb
          npm install --save-dev @electron-forge/maker-rpm
          npx electron-forge import

      - name: Make Artifacts
        run: |
          npm run make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yao-knowledge-windows-x64
          path: |
            out\make\squirrel.windows\x64\*.exe
